### ISSUE TITLE
Unable to create project

### ISSUE THREAD

**Issue by Sytrookie** [idmarinas/lotgd-game#1508] opened 2023-05-05 06:48 UTC
Appreciate the support recently, I've been trying to install this for awhile now as I have a project idea. Sorry for the issue spam - just really excited to start configuring an lotgd.

Now unable to run the `lotgd:skeleton:project:create` command

Console log w/ a fresh installation using wiki instructions:

```
$ composer lotgd:skeleton:project:create
> LoTGD\Skeleton::skeleton

Coping files of LoTGD Core to Skeleton for active commands in local dev.

Finish copy files> LoTGD\Skeleton::core

Coping files of LoTGD Core to "_core_files/" folder

Finish coping files of LoTGD Core to "_core_files/" folder> composer install
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Package sonata-project/cache is abandoned, you should avoid using it. No replacement was suggested.
Package symfony/debug is abandoned, you should avoid using it. Use symfony/error-handler instead.
Package symfony/inflector is abandoned, you should avoid using it. Use EnglishInflector from the String component instead.
Generating optimized autoload files
139 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

Run composer recipes at any time to see the status of your Symfony recipes.

> php bin/console cache:clear

 // Clearing the cache for the dev environment with debug true


In CallableDir.php line 74:

  Invalid object declaration.


cache:clear [--no-warmup] [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>

Script php bin/console cache:clear handling the lotgd:skeleton:project:create event returned with error code 1
```

**Comment by idmarinas** [comment] 2023-05-05 09:33
Hi ^_^

Can you use this command `php bin/console cache:clear -vv`

All installation is ok, only fail when clear symfony cache. May be this command give more info.

**Comment by Sytrookie** [comment] 2023-05-09 15:08
```
$ php bin/console cache:clear -vv

 // Clearing the cache for the dev environment with debug true

 // Warming up cache...


In CallableDir.php line 74:

  [Jaxon\Exception\Error]
  Invalid object declaration.


Exception trace:
  at D:\lotgd\lots\vendor\jaxon-php\jaxon-core\src\Request\Plugin\CallableDir.php:74
 Jaxon\Request\Plugin\CallableDir->checkDirectory() at D:\lotgd\lots\vendor\jaxon-php\jaxon-core\src\R
equest\Plugin\CallableDir.php:125
 Jaxon\Request\Plugin\CallableDir->register() at D:\lotgd\lots\vendor\jaxon-php\jaxon-core\src\Plugin\
Manager.php:232
 Jaxon\Plugin\Manager->registerCallable() at D:\lotgd\lots\vendor\jaxon-php\jaxon-core\src\Jaxon.php:2
72
 Jaxon\Jaxon->register() at D:\lotgd\lots\src\core\Service\Jaxon.php:27
 Lotgd\Core\Service\Jaxon->__construct() at D:\lotgd\lots\var\cache\dev\Container1XbfOsj\coreLotgd_Cor
e_KernelDevDebugContainer.php:2628
 Container1XbfOsj\coreLotgd_Core_KernelDevDebugContainer->getLotgd_Core_JaxonService() at D:\lotgd\lot
s\var\cache\dev\Container1XbfOsj\coreLotgd_Core_KernelDevDebugContainer.php:3786
 Container1XbfOsj\coreLotgd_Core_KernelDevDebugContainer->getTwigService() at D:\lotgd\lots\vendor\sym
fony\dependency-injection\Container.php:448
 Symfony\Component\DependencyInjection\Container->getService() at D:\lotgd\lots\vendor\symfony\depende
ncy-injection\Argument\ServiceLocator.php:42
 Symfony\Component\DependencyInjection\Argument\ServiceLocator->get() at D:\lotgd\lots\vendor\symfony\
twig-bundle\CacheWarmer\TemplateCacheWarmer.php:44
 Symfony\Bundle\TwigBundle\CacheWarmer\TemplateCacheWarmer->warmUp() at D:\lotgd\lots\vendor\symfony\h
ttp-kernel\CacheWarmer\CacheWarmerAggregate.php:97
 Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate->warmUp() at D:\lotgd\lots\vendor\symfo
ny\framework-bundle\Command\CacheClearCommand.php:196
 Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->warmup() at D:\lotgd\lots\vendor\symfony\fr
amework-bundle\Command\CacheClearCommand.php:129
 Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->execute() at D:\lotgd\lots\vendor\symfony\c
onsole\Command\Command.php:255
 Symfony\Component\Console\Command\Command->run() at D:\lotgd\lots\vendor\symfony\console\Application.
php:1039
 Symfony\Component\Console\Application->doRunCommand() at D:\lotgd\lots\vendor\symfony\framework-bundl
e\Console\Application.php:97
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at D:\lotgd\lots\vendor\symfony\co
nsole\Application.php:275
 Symfony\Component\Console\Application->doRun() at D:\lotgd\lots\vendor\symfony\framework-bundle\Conso
le\Application.php:83
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at D:\lotgd\lots\vendor\symfony\console\A
pplication.php:149
 Symfony\Component\Console\Application->run() at D:\lotgd\lots\bin\console:58

cache:clear [--no-warmup] [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|-
-version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
```

**Comment by idmarinas** [comment] 2023-05-09 17:36
Hello:

I think the problem is with jaxon. Check that folders of ajax are created `src/ajax/core` and `src/ajax/local` 

Them ejecute command `php bin/console cache:clear -vv`

**Comment by idmarinas** [comment] 2023-06-02 14:51
I think that the problem is solved, so close this issue

**Closed as completed by idmarinas** 2023-06-02 14:51 UTC
Labels: bug
